### ISSUE TITLE
Update angular CLI

### ISSUE THREAD

**Issue by upkarlidder** [Call-for-Code-for-Racial-Justice/Open-Sentencing-UI#51]
The project currently uses `"@angular/cli": "^8.3.29",`. The latest angular CLI is `12.2.1`. 

@yochanah would it make sense to move to this latest version?

**Comment by RickPoleshuck** [comment]
I am using ^12.0.5 for a personal project. That designation should grab
12.2.1. I consider myself a junior angular programmer, but I would
prefer to use the same versions. :-) On Sun, 2021-08-15 at 19:17 -0700,
Upkar Lidder wrote:

**Comment by yochanah** [comment]
Yes, it's good to move to latest version

**Comment by upkarlidder** [comment]
Thanks @RickPoleshuck. I agree. We should move to 12.x.x from 8.3.29. They follow semantic versioning which, means 12.2.1 and 12.0.5 should theoretically both work.

```
Minor releases contain new smaller features. Minor releases are fully backward-compatible; no developer assistance is expected during update, but you can optionally modify your applications and libraries to begin using new APIs, features, and capabilities that were added in the release. 
```

You can read more here - https://angular.io/guide/releases#angular-versioning

**Comment by RickPoleshuck** [comment]
It is my understanding that the caret in front of ^12.0.5 means that
the minor version will be upgraded automatically, so ^12.0.5 is
effectively 12.2.1 today.  I had to look it up, before I posted. :-)

**Comment by upkarlidder** [comment]
^12.0.5 works for me. @yochanah?

**Comment by demilolu** [comment]
Potential issues with Carbon & Angular CLI @wisdomkeeper.

Or perhaps the issue is with upgrading Angular.

**Comment by sforsyth089** [comment]
Going to stick with old version due to lack of changes in new version. Can revisit at later time.
